name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.1)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Update version in pyproject.toml
      run: |
        sed -i 's/^version = .*/version = "${{ github.event.inputs.version }}"/' pyproject.toml
    
    - name: Commit version bump
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pyproject.toml
        git commit -m "Bump version to ${{ github.event.inputs.version }}"
        git push
    
    - name: Create tag and release
      run: |
        git tag v${{ github.event.inputs.version }}
        git push origin v${{ github.event.inputs.version }}
    
    - name: Generate changelog
      id: changelog
      run: |
        # Get the latest tag before this one
        PREVIOUS_TAG=$(git tag --sort=-version:refname | grep -v "v${{ github.event.inputs.version }}" | head -n 1)
        
        if [ -z "$PREVIOUS_TAG" ]; then
          # If no previous tag, get all commits
          CHANGELOG=$(git log --pretty=format:"* %s (%h)" --reverse)
        else
          # Get commits since the last tag
          CHANGELOG=$(git log ${PREVIOUS_TAG}..HEAD --pretty=format:"* %s (%h)" --reverse)
        fi
        
        # Save changelog to a file and environment variable
        echo "$CHANGELOG" > changelog.txt
        echo "CHANGELOG<<EOF" >> $GITHUB_ENV
        echo "$CHANGELOG" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    
    - name: Build package
      run: |
        uv build
    
    - name: Publish to PyPI
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        uv publish
    
    - name: Create GitHub release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create v${{ github.event.inputs.version }} \
          --title "Release v${{ github.event.inputs.version }}" \
          --notes "${{ env.CHANGELOG }}" \
          ./dist/*
